apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ek958q62d-go-gitops
  description: This is GitOps manifest for ek958q62d-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=ek958q62d-go
    backstage.io/kubernetes-id: ek958q62d-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: ek958q62d-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ek958q62d-go
