apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ek958q62d-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ek958q62d-go 
  name: ek958q62d-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ek958q62d-go 
